In [1]:
import pandas as pd
df = pd.read_csv("dataset.csv")
df # Loaded the dataset successfully in python

,Timestamp,From Bank,Account,To Bank,Account_4,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,9/1/2022 0:14:00,1,8008093B0,1,8008093B0,3480926.29,US Dollar,3480926.29,US Dollar,Reinvestment,0
1,9/1/2022 0:01:00,1,802921370,1,802921370,13743.28,US Dollar,13743.28,US Dollar,Reinvestment,0
2,9/1/2022 9:18:00,1,800DB4EF0,1,800DB4EF0,19.61,US Dollar,19.61,US Dollar,Reinvestment,0
3,9/1/2022 17:57:00,1,80D2D6E70,1,80D2D6E70,7.92,US Dollar,7.92,US Dollar,Reinvestment,0
4,9/6/2022 4:10:00,1,8003080E0,1,800580F30,16.76,US Dollar,16.76,US Dollar,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...
495,9/2/2022 14:20:00,1,800115CA0,10,800171EA0,72.95,US Dollar,72.95,US Dollar,Credit Card,0
496,9/7/2022 2:50:00,1,8006A9500,10,8006B2620,3664.62,US Dollar,3664.62,US Dollar,Cheque,0
497,9/8/2022 20:15:00,1,803D60750,10,80602F070,192.10,US Dollar,192.10,US Dollar,Cheque,0
498,9/9/2022 8:07:00,1,800057020,10,800146140,394.56,US Dollar,394.56,US Dollar,Cheque,0
499,9/7/2022 2:45:00,1,800115AD0,10,800216DF0,8.22,US Dollar,8.22,US Dollar,ACH,0

In [2]:
df.shape

(500, 11)

In [3]:
df.head(15)

,Timestamp,From Bank,Account,To Bank,Account_4,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,9/1/2022 0:14:00,1,8008093B0,1,8008093B0,3480926.29,US Dollar,3480926.29,US Dollar,Reinvestment,0
1,9/1/2022 0:01:00,1,802921370,1,802921370,13743.28,US Dollar,13743.28,US Dollar,Reinvestment,0
2,9/1/2022 9:18:00,1,800DB4EF0,1,800DB4EF0,19.61,US Dollar,19.61,US Dollar,Reinvestment,0
3,9/1/2022 17:57:00,1,80D2D6E70,1,80D2D6E70,7.92,US Dollar,7.92,US Dollar,Reinvestment,0
4,9/6/2022 4:10:00,1,8003080E0,1,800580F30,16.76,US Dollar,16.76,US Dollar,Credit Card,0
5,9/7/2022 10:52:00,1,80005C0A0,1,8002552F0,174.60,US Dollar,174.60,US Dollar,Credit Card,0
6,9/8/2022 9:33:00,1,800456020,1,8023DBC00,787.57,US Dollar,787.57,US Dollar,Credit Card,0
7,9/1/2022 0:26:00,1,8006F01C0,1,8006F01C0,384.52,US Dollar,384.52,US Dollar,Reinvestment,0
8,9/1/2022 0:01:00,1,813837720,1,813837720,55241.41,US Dollar,55241.41,US Dollar,Reinvestment,0
9,9/1/2022 17:17:00,1,8010B63F0,1,801F328B0,534.36,US Dollar,534.36,US Dollar,Cheque,0
10,9/6/2022 10:20:00,1,80024F4A0,1,800327650,15963.95,US Dollar,15963.95,US Dollar,Credit Card,0
11,9/1/2022 0:10:00,1,802343330,1,802343330,6.67,US Dollar,6.67,US Dollar,Reinvestment,0
12,9/1/2022 0:11:00,1,8051C1590,1,8051C1590,955.45,US Dollar,955.45,US Dollar,Reinvestment,0
13,9/1/2022 0:13:00,1,80AEDAE40,1,80AEDAE40,74946.49,US Dollar,74946.49,US Dollar,Reinvestment,0
14,9/1/2022 1:41:00,1,800300E30,1,800300E30,1000.61,Euro,1172.50,US Dollar,ACH,0

In [4]:
df.columns
print("No of columns in dataset", len(df.columns))

No of columns in dataset 11

In [5]:
df.dtypes # The datatypes of each column in the dataset

Timestamp              object
From Bank               int64
Account                object
To Bank                 int64
Account_4              object
Amount Received       float64
Receiving Currency     object
Amount Paid           float64
Payment Currency       object
Payment Format         object
Is Laundering           int64
dtype: object

In [6]:
df.info() # Give your summary of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Timestamp           500 non-null    object
 1   From Bank           500 non-null    int64
 2   Account             500 non-null    object
 3   To Bank             500 non-null    int64
 4   Account_4           500 non-null    object
 5   Amount Received     500 non-null    float64
 6   Receiving Currency  500 non-null    object
 7   Amount Paid         500 non-null    float64
 8   Payment Currency    500 non-null    object
 9   Payment Format      500 non-null    object
 10  Is Laundering       500 non-null    int64
dtypes: float64(2), int64(3), object(6)
memory usage: 43.1+ KB

In [7]:
df.isna().sum().to_frame("Missing Values")

                    Missing Values
Timestamp                        0
From Bank                        0
Account                          0
To Bank                          0
Account_4                        0
Amount Received                  0
Receiving Currency               0
Amount Paid                      0
Payment Currency                 0
Payment Format                   0
Is Laundering                    0

In [8]:
import pandas as pd

In [9]:
dataset = pd.read_csv("HI-Small_Trans.csv") # 453 MB Dataset
dataset.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [10]:
dataset.shape

(5078345, 11)

In [11]:
total_transactions = len(dataset)
total_transactions

5078345

In [12]:
dataset.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering'],
      dtype='object')

In [13]:
dataset['Is Laundering'].unique()

array([0, 1])

In [14]:
print("Total ML Transactions:", int(dataset['Is Laundering'].sum()))

Total ML Transactions: 5177

In [15]:
total_ml_transactions = int(dataset['Is Laundering'].sum())
total_ml_transactions

5177

In [16]:
# Calculate the percentage of transactions of money laundering.
total_ml_transactions / total_transactions

0.0010194266045335635

In [17]:
dataset.dtypes # Schema of your dataset

Timestamp              object
From Bank               int64
Account                object
To Bank                 int64
Account.1              object
Amount Received       float64
Receiving Currency     object
Amount Paid           float64
Payment Currency       object
Payment Format         object
Is Laundering           int64
dtype: object

In [18]:
dataset['Timestamp'].head()

0    2022/09/01 00:20
1    2022/09/01 00:20
2    2022/09/01 00:00
3    2022/09/01 00:02
4    2022/09/01 00:06
Name: Timestamp, dtype: object

In [19]:
dataset.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [20]:
dataset[['Account', 'Account.1']]

           Account  Account.1
0        8000EBD30  8000EBD30
1        8000F4580  8000F5340
2        8000F4670  8000F4670
3        8000F5030  8000F5030
4        8000F5200  8000F5200
...            ...        ...
5078340  8148A6631  8148A8711
5078341  8148A8671  8148A8711
5078342  8148A6771  8148A8711
5078343  8148A6311  8148A8711
5078344  8148A6091  8148A8711

[5078345 rows x 2 columns]

In [21]:
# Define the columns required for safe transaction analysis.
data_contract = {'transaction_timestamp', 
 'from_bank', 'from_account',
 'to_bank', 'to_account',
'amount_paid', 'payment_currency'}
data_contract

{'amount_paid',
 'from_account',
 'from_bank',
 'payment_currency',
 'to_account',
 'to_bank',
 'transaction_timestamp'}

In [22]:
set(dataset.columns)

{'Account',
 'Account.1',
 'Amount Paid',
 'Amount Received',
 'From Bank',
 'Is Laundering',
 'Payment Currency',
 'Payment Format',
 'Receiving Currency',
 'Timestamp',
 'To Bank'}

In [23]:
data_contract - set(dataset.columns)

{'amount_paid',
 'from_account',
 'from_bank',
 'payment_currency',
 'to_account',
 'to_bank',
 'transaction_timestamp'}

In [24]:
missing_columns = sorted(data_contract - set(dataset.columns))
missing_columns

['amount_paid',
 'from_account',
 'from_bank',
 'payment_currency',
 'to_account',
 'to_bank',
 'transaction_timestamp']

In [25]:
# Stop immediately when the data contract is broken.
if missing_columns:
    raise ValueError(f"The following columns are missing {missing_columns}")

ValueError: The following columns are missing ['amount_paid', 'from_account', 'from_bank', 'payment_currency', 'to_account', 'to_bank', 'transaction_timestamp']

In [26]:
import re

In [27]:
def normalise_column_name(name: str) -> str:
    #1 Convert any input label to text and remove outer spaces.
    name = str(name).strip()
    #2 Replace groups of non-alphanumeric characters with one underscore.
    name = re.sub(r"[^0-9a-zA-Z]+", "_", name)
    #3 Collapse repeated underscores and remove underscores at both ends
    name = re.sub(r"_+", "_", name).strip("_")
    #4 Return lowercase snake_case for predictable downstream references.
    return name.lower()

In [28]:
normalise_column_name("_amount$$$%_received")

'amount_received'

In [29]:
text = " from bank "
text.strip()

'from bank'

In [30]:
text = "#amount$$"
re.sub(r"[^0-9a-zA-Z]+", "_", text)

'_amount_'

In [31]:
text = "_amount___Received_"
text = re.sub(r"_+", "_", text).strip("_")
text

'amount_Received'

In [32]:
text.lower()

'amount_received'

In [33]:
dataset.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering'],
      dtype='object')

In [34]:
# Apply the function to every dataframe column.
dataset.columns = [normalise_column_name(column) for column in dataset.columns]
dataset.columns

Index(['timestamp', 'from_bank', 'account', 'to_bank', 'account_1',
       'amount_received', 'receiving_currency', 'amount_paid',
       'payment_currency', 'payment_format', 'is_laundering'],
      dtype='object')

In [35]:
# Detect collisions caused by standardisation.
assert not dataset.columns.duplicated().any(), "Duplicate columns detected"

In [36]:
dataset['timestamp']

0          2022/09/01 00:20
1          2022/09/01 00:20
2          2022/09/01 00:00
3          2022/09/01 00:02
4          2022/09/01 00:06
                 ...
5078340    2022/09/10 23:57
5078341    2022/09/10 23:35
5078342    2022/09/10 23:52
5078343    2022/09/10 23:46
5078344    2022/09/10 23:37
Name: timestamp, Length: 5078345, dtype: object

In [37]:
# Convert the transaction time to a timezone-aware datetime.
import pandas as pd

In [38]:
dataset['timestamp'] = pd.to_datetime(dataset['timestamp'], utc=True, errors='coerce')
dataset['timestamp']

0         2022-09-01 00:20:00+00:00
1         2022-09-01 00:20:00+00:00
2         2022-09-01 00:00:00+00:00
3         2022-09-01 00:02:00+00:00
4         2022-09-01 00:06:00+00:00
                     ...
5078340   2022-09-10 23:57:00+00:00
5078341   2022-09-10 23:35:00+00:00
5078342   2022-09-10 23:52:00+00:00
5078343   2022-09-10 23:46:00+00:00
5078344   2022-09-10 23:37:00+00:00
Name: timestamp, Length: 5078345, dtype: datetime64[ns, UTC]

In [39]:
dataset.dtypes

timestamp             datetime64[ns, UTC]
from_bank                           int64
account                            object
to_bank                             int64
account_1                          object
amount_received                   float64
receiving_currency                 object
amount_paid                       float64
payment_currency                   object
payment_format                     object
is_laundering                       int64
dtype: object

In [40]:
dataset['amount_paid']

0           3697.340000
1              0.010000
2          14675.570000
3           2806.970000
4          36682.970000
               ...
5078340        0.154978
5078341        0.108128
5078342        0.004988
5078343        0.038417
5078344        0.281983
Name: amount_paid, Length: 5078345, dtype: float64

In [41]:
pd.to_numeric(dataset['amount_paid'], errors='coerce')

0           3697.340000
1              0.010000
2          14675.570000
3           2806.970000
4          36682.970000
               ...
5078340        0.154978
5078341        0.108128
5078342        0.004988
5078343        0.038417
5078344        0.281983
Name: amount_paid, Length: 5078345, dtype: float64

In [42]:
dataset.head()

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,is_laundering
0,2022-09-01 00:20:00+00:00,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022-09-01 00:20:00+00:00,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022-09-01 00:00:00+00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022-09-01 00:02:00+00:00,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022-09-01 00:06:00+00:00,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [46]:
[str(dataset[column].dtype) for column in dataset.columns]

['datetime64[ns, UTC]',
 'int64',
 'object',
 'int64',
 'object',
 'float64',
 'object',
 'float64',
 'object',
 'object',
 'int64']

In [54]:
# Count missing values in each column.
# [dataset[column].isna() for column in dataset.columns]
int(dataset['account'].isna().sum()) # This is for single column account
[int(dataset[column].isna().sum()) for column in dataset.columns]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [60]:
int(round(dataset['account'].isna().mean() * 100, 2))
[int(round(dataset[column].isna().mean() * 100, 2)) for column in dataset.columns]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [64]:
# Count distinct values, including missing as a possible state
dataset['account'].nunique(dropna=False)
[dataset[column].nunique(dropna=False) for column in dataset.columns]

[15018, 30470, 496995, 15811, 420636, 915161, 15, 923873, 15, 7, 2]

In [66]:
# DQ = Data Quality profiling - Building a Dataset Health Report
# Build one row of quality statistics for every dataframe column
# pd.DataFrame({key:value}) keys will be treated as columns and values as rows

dq_report = pd.DataFrame({
    "columns": dataset.columns, 
    "dtype": [str(dataset[column].dtype) for column in dataset.columns],
    "missing": [int(dataset[column].isna().sum()) for column in dataset.columns],
    "missing_pct": [int(round(dataset[column].isna().mean() * 100, 2)) for column in dataset.columns],
    "unique_count": [dataset[column].nunique(dropna=False) for column in dataset.columns]
             })

dq_report

,columns,dtype,missing,missing_pct,unique_count
0,timestamp,"datetime64[ns, UTC]",0,0,15018
1,from_bank,int64,0,0,30470
2,account,object,0,0,496995
3,to_bank,int64,0,0,15811
4,account_1,object,0,0,420636
5,amount_received,float64,0,0,915161
6,receiving_currency,object,0,0,15
7,amount_paid,float64,0,0,923873
8,payment_currency,object,0,0,15
9,payment_format,object,0,0,7
10,is_laundering,int64,0,0,2

In [67]:
# Sort the report so the lowest unique_count columns appear first.
dq_report.sort_values("unique_count", ascending=True)

,columns,dtype,missing,missing_pct,unique_count
10,is_laundering,int64,0,0,2
9,payment_format,object,0,0,7
6,receiving_currency,object,0,0,15
8,payment_currency,object,0,0,15
0,timestamp,"datetime64[ns, UTC]",0,0,15018
3,to_bank,int64,0,0,15811
1,from_bank,int64,0,0,30470
4,account_1,object,0,0,420636
2,account,object,0,0,496995
5,amount_received,float64,0,0,915161
7,amount_paid,float64,0,0,923873