In [3]:
import pandas as pd
df = pd.read_csv("dataset.csv")
df # Loaded the dataset successfully in python

,Timestamp,From Bank,Account,To Bank,Account_4,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,9/1/2022 0:14:00,1,8008093B0,1,8008093B0,3480926.29,US Dollar,3480926.29,US Dollar,Reinvestment,0
1,9/1/2022 0:01:00,1,802921370,1,802921370,13743.28,US Dollar,13743.28,US Dollar,Reinvestment,0
2,9/1/2022 9:18:00,1,800DB4EF0,1,800DB4EF0,19.61,US Dollar,19.61,US Dollar,Reinvestment,0
3,9/1/2022 17:57:00,1,80D2D6E70,1,80D2D6E70,7.92,US Dollar,7.92,US Dollar,Reinvestment,0
4,9/6/2022 4:10:00,1,8003080E0,1,800580F30,16.76,US Dollar,16.76,US Dollar,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...
495,9/2/2022 14:20:00,1,800115CA0,10,800171EA0,72.95,US Dollar,72.95,US Dollar,Credit Card,0
496,9/7/2022 2:50:00,1,8006A9500,10,8006B2620,3664.62,US Dollar,3664.62,US Dollar,Cheque,0
497,9/8/2022 20:15:00,1,803D60750,10,80602F070,192.10,US Dollar,192.10,US Dollar,Cheque,0
498,9/9/2022 8:07:00,1,800057020,10,800146140,394.56,US Dollar,394.56,US Dollar,Cheque,0
499,9/7/2022 2:45:00,1,800115AD0,10,800216DF0,8.22,US Dollar,8.22,US Dollar,ACH,0

In [4]:
df.shape

(500, 11)

In [6]:
df.head(15)

,Timestamp,From Bank,Account,To Bank,Account_4,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,9/1/2022 0:14:00,1,8008093B0,1,8008093B0,3480926.29,US Dollar,3480926.29,US Dollar,Reinvestment,0
1,9/1/2022 0:01:00,1,802921370,1,802921370,13743.28,US Dollar,13743.28,US Dollar,Reinvestment,0
2,9/1/2022 9:18:00,1,800DB4EF0,1,800DB4EF0,19.61,US Dollar,19.61,US Dollar,Reinvestment,0
3,9/1/2022 17:57:00,1,80D2D6E70,1,80D2D6E70,7.92,US Dollar,7.92,US Dollar,Reinvestment,0
4,9/6/2022 4:10:00,1,8003080E0,1,800580F30,16.76,US Dollar,16.76,US Dollar,Credit Card,0
5,9/7/2022 10:52:00,1,80005C0A0,1,8002552F0,174.60,US Dollar,174.60,US Dollar,Credit Card,0
6,9/8/2022 9:33:00,1,800456020,1,8023DBC00,787.57,US Dollar,787.57,US Dollar,Credit Card,0
7,9/1/2022 0:26:00,1,8006F01C0,1,8006F01C0,384.52,US Dollar,384.52,US Dollar,Reinvestment,0
8,9/1/2022 0:01:00,1,813837720,1,813837720,55241.41,US Dollar,55241.41,US Dollar,Reinvestment,0
9,9/1/2022 17:17:00,1,8010B63F0,1,801F328B0,534.36,US Dollar,534.36,US Dollar,Cheque,0
10,9/6/2022 10:20:00,1,80024F4A0,1,800327650,15963.95,US Dollar,15963.95,US Dollar,Credit Card,0
11,9/1/2022 0:10:00,1,802343330,1,802343330,6.67,US Dollar,6.67,US Dollar,Reinvestment,0
12,9/1/2022 0:11:00,1,8051C1590,1,8051C1590,955.45,US Dollar,955.45,US Dollar,Reinvestment,0
13,9/1/2022 0:13:00,1,80AEDAE40,1,80AEDAE40,74946.49,US Dollar,74946.49,US Dollar,Reinvestment,0
14,9/1/2022 1:41:00,1,800300E30,1,800300E30,1000.61,Euro,1172.50,US Dollar,ACH,0

In [8]:
df.columns
print("No of columns in dataset", len(df.columns))

No of columns in dataset 11

In [9]:
df.dtypes # The datatypes of each column in the dataset

Timestamp              object
From Bank               int64
Account                object
To Bank                 int64
Account_4              object
Amount Received       float64
Receiving Currency     object
Amount Paid           float64
Payment Currency       object
Payment Format         object
Is Laundering           int64
dtype: object

In [11]:
df.info() # Give your summary of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Timestamp           500 non-null    object
 1   From Bank           500 non-null    int64
 2   Account             500 non-null    object
 3   To Bank             500 non-null    int64
 4   Account_4           500 non-null    object
 5   Amount Received     500 non-null    float64
 6   Receiving Currency  500 non-null    object
 7   Amount Paid         500 non-null    float64
 8   Payment Currency    500 non-null    object
 9   Payment Format      500 non-null    object
 10  Is Laundering       500 non-null    int64
dtypes: float64(2), int64(3), object(6)
memory usage: 43.1+ KB

In [14]:
df.isna().sum().to_frame("Missing Values")

                    Missing Values
Timestamp                        0
From Bank                        0
Account                          0
To Bank                          0
Account_4                        0
Amount Received                  0
Receiving Currency               0
Amount Paid                      0
Payment Currency                 0
Payment Format                   0
Is Laundering                    0