In [1]:
import pandas as pd
df = pd.read_csv("dataset.csv")
df # Loaded the dataset successfully in python

,Timestamp,From Bank,Account,To Bank,Account_4,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,9/1/2022 0:14:00,1,8008093B0,1,8008093B0,3480926.29,US Dollar,3480926.29,US Dollar,Reinvestment,0
1,9/1/2022 0:01:00,1,802921370,1,802921370,13743.28,US Dollar,13743.28,US Dollar,Reinvestment,0
2,9/1/2022 9:18:00,1,800DB4EF0,1,800DB4EF0,19.61,US Dollar,19.61,US Dollar,Reinvestment,0
3,9/1/2022 17:57:00,1,80D2D6E70,1,80D2D6E70,7.92,US Dollar,7.92,US Dollar,Reinvestment,0
4,9/6/2022 4:10:00,1,8003080E0,1,800580F30,16.76,US Dollar,16.76,US Dollar,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...
495,9/2/2022 14:20:00,1,800115CA0,10,800171EA0,72.95,US Dollar,72.95,US Dollar,Credit Card,0
496,9/7/2022 2:50:00,1,8006A9500,10,8006B2620,3664.62,US Dollar,3664.62,US Dollar,Cheque,0
497,9/8/2022 20:15:00,1,803D60750,10,80602F070,192.10,US Dollar,192.10,US Dollar,Cheque,0
498,9/9/2022 8:07:00,1,800057020,10,800146140,394.56,US Dollar,394.56,US Dollar,Cheque,0
499,9/7/2022 2:45:00,1,800115AD0,10,800216DF0,8.22,US Dollar,8.22,US Dollar,ACH,0

In [2]:
df.shape

(500, 11)

In [3]:
df.head(15)

,Timestamp,From Bank,Account,To Bank,Account_4,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,9/1/2022 0:14:00,1,8008093B0,1,8008093B0,3480926.29,US Dollar,3480926.29,US Dollar,Reinvestment,0
1,9/1/2022 0:01:00,1,802921370,1,802921370,13743.28,US Dollar,13743.28,US Dollar,Reinvestment,0
2,9/1/2022 9:18:00,1,800DB4EF0,1,800DB4EF0,19.61,US Dollar,19.61,US Dollar,Reinvestment,0
3,9/1/2022 17:57:00,1,80D2D6E70,1,80D2D6E70,7.92,US Dollar,7.92,US Dollar,Reinvestment,0
4,9/6/2022 4:10:00,1,8003080E0,1,800580F30,16.76,US Dollar,16.76,US Dollar,Credit Card,0
5,9/7/2022 10:52:00,1,80005C0A0,1,8002552F0,174.60,US Dollar,174.60,US Dollar,Credit Card,0
6,9/8/2022 9:33:00,1,800456020,1,8023DBC00,787.57,US Dollar,787.57,US Dollar,Credit Card,0
7,9/1/2022 0:26:00,1,8006F01C0,1,8006F01C0,384.52,US Dollar,384.52,US Dollar,Reinvestment,0
8,9/1/2022 0:01:00,1,813837720,1,813837720,55241.41,US Dollar,55241.41,US Dollar,Reinvestment,0
9,9/1/2022 17:17:00,1,8010B63F0,1,801F328B0,534.36,US Dollar,534.36,US Dollar,Cheque,0
10,9/6/2022 10:20:00,1,80024F4A0,1,800327650,15963.95,US Dollar,15963.95,US Dollar,Credit Card,0
11,9/1/2022 0:10:00,1,802343330,1,802343330,6.67,US Dollar,6.67,US Dollar,Reinvestment,0
12,9/1/2022 0:11:00,1,8051C1590,1,8051C1590,955.45,US Dollar,955.45,US Dollar,Reinvestment,0
13,9/1/2022 0:13:00,1,80AEDAE40,1,80AEDAE40,74946.49,US Dollar,74946.49,US Dollar,Reinvestment,0
14,9/1/2022 1:41:00,1,800300E30,1,800300E30,1000.61,Euro,1172.50,US Dollar,ACH,0

In [4]:
df.columns
print("No of columns in dataset", len(df.columns))

No of columns in dataset 11

In [5]:
df.dtypes # The datatypes of each column in the dataset

Timestamp              object
From Bank               int64
Account                object
To Bank                 int64
Account_4              object
Amount Received       float64
Receiving Currency     object
Amount Paid           float64
Payment Currency       object
Payment Format         object
Is Laundering           int64
dtype: object

In [6]:
df.info() # Give your summary of the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Timestamp           500 non-null    object
 1   From Bank           500 non-null    int64
 2   Account             500 non-null    object
 3   To Bank             500 non-null    int64
 4   Account_4           500 non-null    object
 5   Amount Received     500 non-null    float64
 6   Receiving Currency  500 non-null    object
 7   Amount Paid         500 non-null    float64
 8   Payment Currency    500 non-null    object
 9   Payment Format      500 non-null    object
 10  Is Laundering       500 non-null    int64
dtypes: float64(2), int64(3), object(6)
memory usage: 43.1+ KB

In [7]:
df.isna().sum().to_frame("Missing Values")

                    Missing Values
Timestamp                        0
From Bank                        0
Account                          0
To Bank                          0
Account_4                        0
Amount Received                  0
Receiving Currency               0
Amount Paid                      0
Payment Currency                 0
Payment Format                   0
Is Laundering                    0

In [8]:
import pandas as pd

In [9]:
dataset = pd.read_csv("HI-Small_Trans.csv") # 453 MB Dataset
dataset.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [10]:
dataset.shape

(5078345, 11)

In [11]:
total_transactions = len(dataset)
total_transactions

5078345

In [12]:
dataset.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering'],
      dtype='object')

In [13]:
dataset['Is Laundering'].unique()

array([0, 1])

In [14]:
print("Total ML Transactions:", int(dataset['Is Laundering'].sum()))

Total ML Transactions: 5177

In [15]:
total_ml_transactions = int(dataset['Is Laundering'].sum())
total_ml_transactions

5177

In [16]:
# Calculate the percentage of transactions of money laundering.
total_ml_transactions / total_transactions

0.0010194266045335635

In [17]:
dataset.dtypes # Schema of your dataset

Timestamp              object
From Bank               int64
Account                object
To Bank                 int64
Account.1              object
Amount Received       float64
Receiving Currency     object
Amount Paid           float64
Payment Currency       object
Payment Format         object
Is Laundering           int64
dtype: object

In [18]:
dataset['Timestamp'].head()

0    2022/09/01 00:20
1    2022/09/01 00:20
2    2022/09/01 00:00
3    2022/09/01 00:02
4    2022/09/01 00:06
Name: Timestamp, dtype: object

In [19]:
dataset.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [20]:
dataset[['Account', 'Account.1']]

           Account  Account.1
0        8000EBD30  8000EBD30
1        8000F4580  8000F5340
2        8000F4670  8000F4670
3        8000F5030  8000F5030
4        8000F5200  8000F5200
...            ...        ...
5078340  8148A6631  8148A8711
5078341  8148A8671  8148A8711
5078342  8148A6771  8148A8711
5078343  8148A6311  8148A8711
5078344  8148A6091  8148A8711

[5078345 rows x 2 columns]

In [21]:
# Define the columns required for safe transaction analysis.
data_contract = {'transaction_timestamp', 
 'from_bank', 'from_account',
 'to_bank', 'to_account',
'amount_paid', 'payment_currency'}
data_contract

{'amount_paid',
 'from_account',
 'from_bank',
 'payment_currency',
 'to_account',
 'to_bank',
 'transaction_timestamp'}

In [22]:
set(dataset.columns)

{'Account',
 'Account.1',
 'Amount Paid',
 'Amount Received',
 'From Bank',
 'Is Laundering',
 'Payment Currency',
 'Payment Format',
 'Receiving Currency',
 'Timestamp',
 'To Bank'}

In [23]:
data_contract - set(dataset.columns)

{'amount_paid',
 'from_account',
 'from_bank',
 'payment_currency',
 'to_account',
 'to_bank',
 'transaction_timestamp'}

In [24]:
missing_columns = sorted(data_contract - set(dataset.columns))
missing_columns

['amount_paid',
 'from_account',
 'from_bank',
 'payment_currency',
 'to_account',
 'to_bank',
 'transaction_timestamp']

In [25]:
# Stop immediately when the data contract is broken.
if missing_columns:
    raise ValueError(f"The following columns are missing {missing_columns}")

ValueError: The following columns are missing ['amount_paid', 'from_account', 'from_bank', 'payment_currency', 'to_account', 'to_bank', 'transaction_timestamp']

In [26]:
import re

In [27]:
def normalise_column_name(name: str) -> str:
    #1 Convert any input label to text and remove outer spaces.
    name = str(name).strip()
    #2 Replace groups of non-alphanumeric characters with one underscore.
    name = re.sub(r"[^0-9a-zA-Z]+", "_", name)
    #3 Collapse repeated underscores and remove underscores at both ends
    name = re.sub(r"_+", "_", name).strip("_")
    #4 Return lowercase snake_case for predictable downstream references.
    return name.lower()

In [28]:
normalise_column_name("_amount$$$%_received")

'amount_received'

In [29]:
text = " from bank "
text.strip()

'from bank'

In [30]:
text = "#amount$$"
re.sub(r"[^0-9a-zA-Z]+", "_", text)

'_amount_'

In [31]:
text = "_amount___Received_"
text = re.sub(r"_+", "_", text).strip("_")
text

'amount_Received'

In [32]:
text.lower()

'amount_received'

In [33]:
dataset.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering'],
      dtype='object')

In [34]:
# Apply the function to every dataframe column.
dataset.columns = [normalise_column_name(column) for column in dataset.columns]
dataset.columns

Index(['timestamp', 'from_bank', 'account', 'to_bank', 'account_1',
       'amount_received', 'receiving_currency', 'amount_paid',
       'payment_currency', 'payment_format', 'is_laundering'],
      dtype='object')

In [35]:
# Detect collisions caused by standardisation.
assert not dataset.columns.duplicated().any(), "Duplicate columns detected"

In [36]:
dataset['timestamp']

0          2022/09/01 00:20
1          2022/09/01 00:20
2          2022/09/01 00:00
3          2022/09/01 00:02
4          2022/09/01 00:06
                 ...
5078340    2022/09/10 23:57
5078341    2022/09/10 23:35
5078342    2022/09/10 23:52
5078343    2022/09/10 23:46
5078344    2022/09/10 23:37
Name: timestamp, Length: 5078345, dtype: object

In [37]:
# Convert the transaction time to a timezone-aware datetime.
import pandas as pd

In [38]:
dataset['timestamp'] = pd.to_datetime(dataset['timestamp'], utc=True, errors='coerce')
dataset['timestamp']

0         2022-09-01 00:20:00+00:00
1         2022-09-01 00:20:00+00:00
2         2022-09-01 00:00:00+00:00
3         2022-09-01 00:02:00+00:00
4         2022-09-01 00:06:00+00:00
                     ...
5078340   2022-09-10 23:57:00+00:00
5078341   2022-09-10 23:35:00+00:00
5078342   2022-09-10 23:52:00+00:00
5078343   2022-09-10 23:46:00+00:00
5078344   2022-09-10 23:37:00+00:00
Name: timestamp, Length: 5078345, dtype: datetime64[ns, UTC]

In [39]:
dataset.dtypes

timestamp             datetime64[ns, UTC]
from_bank                           int64
account                            object
to_bank                             int64
account_1                          object
amount_received                   float64
receiving_currency                 object
amount_paid                       float64
payment_currency                   object
payment_format                     object
is_laundering                       int64
dtype: object

In [40]:
dataset['amount_paid']

0           3697.340000
1              0.010000
2          14675.570000
3           2806.970000
4          36682.970000
               ...
5078340        0.154978
5078341        0.108128
5078342        0.004988
5078343        0.038417
5078344        0.281983
Name: amount_paid, Length: 5078345, dtype: float64

In [41]:
pd.to_numeric(dataset['amount_paid'], errors='coerce')

0           3697.340000
1              0.010000
2          14675.570000
3           2806.970000
4          36682.970000
               ...
5078340        0.154978
5078341        0.108128
5078342        0.004988
5078343        0.038417
5078344        0.281983
Name: amount_paid, Length: 5078345, dtype: float64

In [42]:
dataset.head()

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,is_laundering
0,2022-09-01 00:20:00+00:00,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022-09-01 00:20:00+00:00,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022-09-01 00:00:00+00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022-09-01 00:02:00+00:00,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022-09-01 00:06:00+00:00,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [43]:
[str(dataset[column].dtype) for column in dataset.columns]

['datetime64[ns, UTC]',
 'int64',
 'object',
 'int64',
 'object',
 'float64',
 'object',
 'float64',
 'object',
 'object',
 'int64']

In [44]:
# Count missing values in each column.
# [dataset[column].isna() for column in dataset.columns]
int(dataset['account'].isna().sum()) # This is for single column account
[int(dataset[column].isna().sum()) for column in dataset.columns]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [45]:
int(round(dataset['account'].isna().mean() * 100, 2))
[int(round(dataset[column].isna().mean() * 100, 2)) for column in dataset.columns]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [46]:
# Count distinct values, including missing as a possible state
dataset['account'].nunique(dropna=False)
[dataset[column].nunique(dropna=False) for column in dataset.columns]

[15018, 30470, 496995, 15811, 420636, 915161, 15, 923873, 15, 7, 2]

In [47]:
# DQ = Data Quality profiling - Building a Dataset Health Report
# Build one row of quality statistics for every dataframe column
# pd.DataFrame({key:value}) keys will be treated as columns and values as rows

dq_report = pd.DataFrame({
    "columns": dataset.columns, 
    "dtype": [str(dataset[column].dtype) for column in dataset.columns],
    "missing": [int(dataset[column].isna().sum()) for column in dataset.columns],
    "missing_pct": [int(round(dataset[column].isna().mean() * 100, 2)) for column in dataset.columns],
    "unique_count": [dataset[column].nunique(dropna=False) for column in dataset.columns]
             })

dq_report

,columns,dtype,missing,missing_pct,unique_count
0,timestamp,"datetime64[ns, UTC]",0,0,15018
1,from_bank,int64,0,0,30470
2,account,object,0,0,496995
3,to_bank,int64,0,0,15811
4,account_1,object,0,0,420636
5,amount_received,float64,0,0,915161
6,receiving_currency,object,0,0,15
7,amount_paid,float64,0,0,923873
8,payment_currency,object,0,0,15
9,payment_format,object,0,0,7
10,is_laundering,int64,0,0,2

In [48]:
# Sort the report so the lowest unique_count columns appear first.
dq_report.sort_values("unique_count", ascending=True)

,columns,dtype,missing,missing_pct,unique_count
10,is_laundering,int64,0,0,2
9,payment_format,object,0,0,7
6,receiving_currency,object,0,0,15
8,payment_currency,object,0,0,15
0,timestamp,"datetime64[ns, UTC]",0,0,15018
3,to_bank,int64,0,0,15811
1,from_bank,int64,0,0,30470
4,account_1,object,0,0,420636
2,account,object,0,0,496995
5,amount_received,float64,0,0,915161
7,amount_paid,float64,0,0,923873

In [49]:
dataset.columns

Index(['timestamp', 'from_bank', 'account', 'to_bank', 'account_1',
       'amount_received', 'receiving_currency', 'amount_paid',
       'payment_currency', 'payment_format', 'is_laundering'],
      dtype='object')

In [50]:
dataset['sender_entity'] = (dataset['from_bank'].astype(str).str.strip()
+ "::" + dataset['account'].astype(str).str.strip())
dataset['sender_entity']

0              10::8000EBD30
1            3208::8000F4580
2            3209::8000F4670
3              12::8000F5030
4              10::8000F5200
                 ...
5078340     54219::8148A6631
5078341        15::8148A8671
5078342    154365::8148A6771
5078343    256398::8148A6311
5078344    154518::8148A6091
Name: sender_entity, Length: 5078345, dtype: object

In [51]:
dataset['receiver_entity'] = (dataset['to_bank'].astype(str).str.strip() 
 + "::" + dataset['account_1'].astype(str).str.strip())

In [52]:
dataset['transaction_id'] = (dataset.index.astype(str) + "-" + dataset['timestamp'].astype(str))

In [53]:
dataset.head()

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,is_laundering,sender_entity,receiver_entity,transaction_id
0,2022-09-01 00:20:00+00:00,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0,10::8000EBD30,10::8000EBD30,0-2022-09-01 00:20:00+00:00
1,2022-09-01 00:20:00+00:00,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0,3208::8000F4580,1::8000F5340,1-2022-09-01 00:20:00+00:00
2,2022-09-01 00:00:00+00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0,3209::8000F4670,3209::8000F4670,2-2022-09-01 00:00:00+00:00
3,2022-09-01 00:02:00+00:00,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0,12::8000F5030,12::8000F5030,3-2022-09-01 00:02:00+00:00
4,2022-09-01 00:06:00+00:00,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0,10::8000F5200,10::8000F5200,4-2022-09-01 00:06:00+00:00

In [54]:
# Sort transactions before calculating time-dependent behaviour.
dataset = dataset.sort_values(['sender_entity', 'timestamp']).copy()
dataset

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,is_laundering,sender_entity,receiver_entity,transaction_id
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,0,10057::803A115E0,10057::803A115E0,213094-2022-09-01 00:19:00+00:00
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,0,10057::803A115E0,29467::803E020C0,824237-2022-09-01 15:00:00+00:00
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,0,10057::803A115E0,29467::803E020C0,824238-2022-09-01 15:02:00+00:00
1541411,2022-09-02 13:03:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,0,10057::803A115E0,29467::803E020C0,1541411-2022-09-02 13:03:00+00:00
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,0,10057::803A115E0,29467::803E020C0,1541410-2022-09-02 13:05:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892752,2022-09-01 17:00:00+00:00,9,8074FDFF0,9,8074FDFF0,3481092.47,Ruble,3481092.47,Ruble,Reinvestment,0,9::8074FDFF0,9::8074FDFF0,892752-2022-09-01 17:00:00+00:00
641019,2022-09-01 09:53:00+00:00,9,8074FF440,9,8074FF440,4434071.16,Ruble,4434071.16,Ruble,Reinvestment,0,9::8074FF440,9::8074FF440,641019-2022-09-01 09:53:00+00:00
244392,2022-09-01 00:02:00+00:00,9,8075352F0,9,8075352F0,63015743.94,Ruble,63015743.94,Ruble,Reinvestment,0,9::8075352F0,9::8075352F0,244392-2022-09-01 00:02:00+00:00
557982,2022-09-01 07:01:00+00:00,9,8075352F0,9,8075352F0,592.46,Ruble,592.46,Ruble,Reinvestment,0,9::8075352F0,9::8075352F0,557982-2022-09-01 07:01:00+00:00
244394,2022-09-01 00:16:00+00:00,9,8075370F0,9,8075370F0,30368.50,Ruble,30368.50,Ruble,Reinvestment,0,9::8075370F0,9::8075370F0,244394-2022-09-01 00:16:00+00:00

In [55]:
dataset['transaction_date'] = dataset['timestamp'].dt.date

In [56]:
dataset['sender_daily_txn_count'] = dataset.groupby(['sender_entity', 'transaction_date'])['transaction_id'].transform("count")

In [57]:
dataset

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,is_laundering,sender_entity,receiver_entity,transaction_id,transaction_date,sender_daily_txn_count
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,0,10057::803A115E0,10057::803A115E0,213094-2022-09-01 00:19:00+00:00,2022-09-01,3
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,0,10057::803A115E0,29467::803E020C0,824237-2022-09-01 15:00:00+00:00,2022-09-01,3
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,0,10057::803A115E0,29467::803E020C0,824238-2022-09-01 15:02:00+00:00,2022-09-01,3
1541411,2022-09-02 13:03:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,0,10057::803A115E0,29467::803E020C0,1541411-2022-09-02 13:03:00+00:00,2022-09-02,2
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,0,10057::803A115E0,29467::803E020C0,1541410-2022-09-02 13:05:00+00:00,2022-09-02,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892752,2022-09-01 17:00:00+00:00,9,8074FDFF0,9,8074FDFF0,3481092.47,Ruble,3481092.47,Ruble,Reinvestment,0,9::8074FDFF0,9::8074FDFF0,892752-2022-09-01 17:00:00+00:00,2022-09-01,2
641019,2022-09-01 09:53:00+00:00,9,8074FF440,9,8074FF440,4434071.16,Ruble,4434071.16,Ruble,Reinvestment,0,9::8074FF440,9::8074FF440,641019-2022-09-01 09:53:00+00:00,2022-09-01,1
244392,2022-09-01 00:02:00+00:00,9,8075352F0,9,8075352F0,63015743.94,Ruble,63015743.94,Ruble,Reinvestment,0,9::8075352F0,9::8075352F0,244392-2022-09-01 00:02:00+00:00,2022-09-01,2
557982,2022-09-01 07:01:00+00:00,9,8075352F0,9,8075352F0,592.46,Ruble,592.46,Ruble,Reinvestment,0,9::8075352F0,9::8075352F0,557982-2022-09-01 07:01:00+00:00,2022-09-01,2
244394,2022-09-01 00:16:00+00:00,9,8075370F0,9,8075370F0,30368.50,Ruble,30368.50,Ruble,Reinvestment,0,9::8075370F0,9::8075370F0,244394-2022-09-01 00:16:00+00:00,2022-09-01,1

In [58]:
dataset['sender_daily_amount'] = dataset.groupby(['sender_entity', 'transaction_date'])["amount_paid"].transform("sum")

In [59]:
dataset['sender_daily_unique_receivers'] = dataset.groupby(['sender_entity', 'transaction_date'])['receiver_entity'].transform("nunique")

In [60]:
dataset['previous_sender_timestamp'] = dataset.groupby('sender_entity')['timestamp'].shift(1)
dataset['previous_sender_timestamp']

213094                          NaT
824237    2022-09-01 00:19:00+00:00
824238    2022-09-01 15:00:00+00:00
1541411   2022-09-01 15:02:00+00:00
1541410   2022-09-02 13:03:00+00:00
                     ...
892752    2022-09-01 00:25:00+00:00
641019                          NaT
244392                          NaT
557982    2022-09-01 00:02:00+00:00
244394                          NaT
Name: previous_sender_timestamp, Length: 5078345, dtype: datetime64[ns, UTC]

In [61]:
dataset['mins_since_previous_sender_transaction'] = (dataset['timestamp'] - dataset['previous_sender_timestamp']).dt.total_seconds() / 60.0
dataset['mins_since_previous_sender_transaction']

213094        NaN
824237      881.0
824238        2.0
1541411    1321.0
1541410       2.0
            ...
892752      995.0
641019        NaN
244392        NaN
557982      419.0
244394        NaN
Name: mins_since_previous_sender_transaction, Length: 5078345, dtype: float64

In [62]:
dataset[dataset['mins_since_previous_sender_transaction'].between(0, 10, inclusive="both") == True]

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,is_laundering,sender_entity,receiver_entity,transaction_id,transaction_date,sender_daily_txn_count,sender_daily_amount,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,0,10057::803A115E0,29467::803E020C0,824238-2022-09-01 15:02:00+00:00,2022-09-01,3,1615413.57,2,2022-09-01 15:00:00+00:00,2.0
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,0,10057::803A115E0,29467::803E020C0,1541410-2022-09-02 13:05:00+00:00,2022-09-02,2,1468459.30,1,2022-09-02 13:03:00+00:00,2.0
2570346,2022-09-05 13:59:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,0,10057::803A115E0,29467::803E020C0,2570346-2022-09-05 13:59:00+00:00,2022-09-05,2,1468459.30,1,2022-09-05 13:53:00+00:00,6.0
3437163,2022-09-07 08:49:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,0,10057::803A115E0,29467::803E020C0,3437163-2022-09-07 08:49:00+00:00,2022-09-07,2,1468459.30,1,2022-09-07 08:47:00+00:00,2.0
4278715,2022-09-09 01:37:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,0,10057::803A115E0,29467::803E020C0,4278715-2022-09-09 01:37:00+00:00,2022-09-09,2,1468459.30,1,2022-09-09 01:37:00+00:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2799136,2022-09-06 00:59:00+00:00,9,8073D58F0,218783,8073D4970,212543.02,Ruble,212543.02,Ruble,Credit Card,0,9::8073D58F0,218783::8073D4970,2799136-2022-09-06 00:59:00+00:00,2022-09-06,2,252144.42,1,2022-09-06 00:51:00+00:00,8.0
3968856,2022-09-08 11:09:00+00:00,9,8073D58F0,218783,8073D4970,39601.40,Ruble,39601.40,Ruble,Cheque,0,9::8073D58F0,218783::8073D4970,3968856-2022-09-08 11:09:00+00:00,2022-09-08,2,252144.42,1,2022-09-08 11:04:00+00:00,5.0
4426635,2022-09-09 07:11:00+00:00,9,8073D58F0,218783,8073D4970,39601.40,Ruble,39601.40,Ruble,Cheque,0,9::8073D58F0,218783::8073D4970,4426635-2022-09-09 07:11:00+00:00,2022-09-09,2,252144.42,1,2022-09-09 07:08:00+00:00,3.0
1883842,2022-09-03 00:08:00+00:00,9,807446D50,2627,802554D70,186.68,US Dollar,186.68,US Dollar,Credit Card,0,9::807446D50,2627::802554D70,1883842-2022-09-03 00:08:00+00:00,2022-09-03,2,14711.17,2,2022-09-03 00:08:00+00:00,0.0
1481559,2022-09-02 11:21:00+00:00,9,8074BAB50,219570,8075370A0,53638.10,Ruble,53638.10,Ruble,Cheque,0,9::8074BAB50,219570::8075370A0,1481559-2022-09-02 11:21:00+00:00,2022-09-02,2,205749.05,1,2022-09-02 11:12:00+00:00,9.0

In [63]:
dataset["rapid_repeat_transfer"] = (
 dataset["mins_since_previous_sender_transaction"]
 .between(0, 10, inclusive="both")
 .fillna(False)
 .astype(int)
)
dataset.head()

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,sender_entity,receiver_entity,transaction_id,transaction_date,sender_daily_txn_count,sender_daily_amount,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,...,10057::803A115E0,10057::803A115E0,213094-2022-09-01 00:19:00+00:00,2022-09-01,3,1615413.57,2,NaT,NaN,0
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,10057::803A115E0,29467::803E020C0,824237-2022-09-01 15:00:00+00:00,2022-09-01,3,1615413.57,2,2022-09-01 00:19:00+00:00,881.0,0
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,10057::803A115E0,29467::803E020C0,824238-2022-09-01 15:02:00+00:00,2022-09-01,3,1615413.57,2,2022-09-01 15:00:00+00:00,2.0,1
1541411,2022-09-02 13:03:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,10057::803A115E0,29467::803E020C0,1541411-2022-09-02 13:03:00+00:00,2022-09-02,2,1468459.30,1,2022-09-01 15:02:00+00:00,1321.0,0
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,10057::803A115E0,29467::803E020C0,1541410-2022-09-02 13:05:00+00:00,2022-09-02,2,1468459.30,1,2022-09-02 13:03:00+00:00,2.0,1

In [64]:
dataset.columns

Index(['timestamp', 'from_bank', 'account', 'to_bank', 'account_1',
       'amount_received', 'receiving_currency', 'amount_paid',
       'payment_currency', 'payment_format', 'is_laundering', 'sender_entity',
       'receiver_entity', 'transaction_id', 'transaction_date',
       'sender_daily_txn_count', 'sender_daily_amount',
       'sender_daily_unique_receivers', 'previous_sender_timestamp',
       'mins_since_previous_sender_transaction', 'rapid_repeat_transfer'],
      dtype='object')

In [65]:
dataset['receiver_unique_senders'] = dataset.groupby('receiver_entity')['sender_entity'].transform("nunique")

In [66]:
dataset.head()

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,receiver_entity,transaction_id,transaction_date,sender_daily_txn_count,sender_daily_amount,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,...,10057::803A115E0,213094-2022-09-01 00:19:00+00:00,2022-09-01,3,1615413.57,2,NaT,NaN,0,1
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,29467::803E020C0,824237-2022-09-01 15:00:00+00:00,2022-09-01,3,1615413.57,2,2022-09-01 00:19:00+00:00,881.0,0,3
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,29467::803E020C0,824238-2022-09-01 15:02:00+00:00,2022-09-01,3,1615413.57,2,2022-09-01 15:00:00+00:00,2.0,1,3
1541411,2022-09-02 13:03:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,29467::803E020C0,1541411-2022-09-02 13:03:00+00:00,2022-09-02,2,1468459.30,1,2022-09-01 15:02:00+00:00,1321.0,0,3
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,29467::803E020C0,1541410-2022-09-02 13:05:00+00:00,2022-09-02,2,1468459.30,1,2022-09-02 13:03:00+00:00,2.0,1,3

In [67]:
dataset['high_fan_in_receiver'] = (dataset['receiver_unique_senders'] >= 5).astype(int)
dataset.head()

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,transaction_id,transaction_date,sender_daily_txn_count,sender_daily_amount,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders,high_fan_in_receiver
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,...,213094-2022-09-01 00:19:00+00:00,2022-09-01,3,1615413.57,2,NaT,NaN,0,1,0
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,824237-2022-09-01 15:00:00+00:00,2022-09-01,3,1615413.57,2,2022-09-01 00:19:00+00:00,881.0,0,3,0
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,824238-2022-09-01 15:02:00+00:00,2022-09-01,3,1615413.57,2,2022-09-01 15:00:00+00:00,2.0,1,3,0
1541411,2022-09-02 13:03:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1541411-2022-09-02 13:03:00+00:00,2022-09-02,2,1468459.30,1,2022-09-01 15:02:00+00:00,1321.0,0,3,0
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1541410-2022-09-02 13:05:00+00:00,2022-09-02,2,1468459.30,1,2022-09-02 13:03:00+00:00,2.0,1,3,0

In [68]:
dataset

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,transaction_id,transaction_date,sender_daily_txn_count,sender_daily_amount,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders,high_fan_in_receiver
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,...,213094-2022-09-01 00:19:00+00:00,2022-09-01,3,1615413.57,2,NaT,NaN,0,1,0
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,824237-2022-09-01 15:00:00+00:00,2022-09-01,3,1615413.57,2,2022-09-01 00:19:00+00:00,881.0,0,3,0
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,824238-2022-09-01 15:02:00+00:00,2022-09-01,3,1615413.57,2,2022-09-01 15:00:00+00:00,2.0,1,3,0
1541411,2022-09-02 13:03:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1541411-2022-09-02 13:03:00+00:00,2022-09-02,2,1468459.30,1,2022-09-01 15:02:00+00:00,1321.0,0,3,0
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1541410-2022-09-02 13:05:00+00:00,2022-09-02,2,1468459.30,1,2022-09-02 13:03:00+00:00,2.0,1,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892752,2022-09-01 17:00:00+00:00,9,8074FDFF0,9,8074FDFF0,3481092.47,Ruble,3481092.47,Ruble,Reinvestment,...,892752-2022-09-01 17:00:00+00:00,2022-09-01,2,3482015.29,1,2022-09-01 00:25:00+00:00,995.0,0,4,0
641019,2022-09-01 09:53:00+00:00,9,8074FF440,9,8074FF440,4434071.16,Ruble,4434071.16,Ruble,Reinvestment,...,641019-2022-09-01 09:53:00+00:00,2022-09-01,1,4434071.16,1,NaT,NaN,0,3,0
244392,2022-09-01 00:02:00+00:00,9,8075352F0,9,8075352F0,63015743.94,Ruble,63015743.94,Ruble,Reinvestment,...,244392-2022-09-01 00:02:00+00:00,2022-09-01,2,63016336.40,1,NaT,NaN,0,5,1
557982,2022-09-01 07:01:00+00:00,9,8075352F0,9,8075352F0,592.46,Ruble,592.46,Ruble,Reinvestment,...,557982-2022-09-01 07:01:00+00:00,2022-09-01,2,63016336.40,1,2022-09-01 00:02:00+00:00,419.0,0,5,1
244394,2022-09-01 00:16:00+00:00,9,8075370F0,9,8075370F0,30368.50,Ruble,30368.50,Ruble,Reinvestment,...,244394-2022-09-01 00:16:00+00:00,2022-09-01,1,30368.50,1,NaT,NaN,0,3,0

In [69]:
dataset.columns

Index(['timestamp', 'from_bank', 'account', 'to_bank', 'account_1',
       'amount_received', 'receiving_currency', 'amount_paid',
       'payment_currency', 'payment_format', 'is_laundering', 'sender_entity',
       'receiver_entity', 'transaction_id', 'transaction_date',
       'sender_daily_txn_count', 'sender_daily_amount',
       'sender_daily_unique_receivers', 'previous_sender_timestamp',
       'mins_since_previous_sender_transaction', 'rapid_repeat_transfer',
       'receiver_unique_senders', 'high_fan_in_receiver'],
      dtype='object')

In [70]:
sender_mean = dataset.groupby("sender_entity")["amount_paid"].transform("mean")
sender_mean

213094     6.950780e+05
824237     6.950780e+05
824238     6.950780e+05
1541411    6.950780e+05
1541410    6.950780e+05
               ...
892752     1.741008e+06
641019     4.434071e+06
244392     3.150817e+07
557982     3.150817e+07
244394     3.036850e+04
Name: amount_paid, Length: 5078345, dtype: float64

In [71]:
sender_std = dataset.groupby("sender_entity")["amount_paid"].transform("std")
sender_std

213094     1.606187e+05
824237     1.606187e+05
824238     1.606187e+05
1541411    1.606187e+05
1541410    1.606187e+05
               ...
892752     2.460852e+06
641019              NaN
244392     4.455844e+07
557982     4.455844e+07
244394              NaN
Name: amount_paid, Length: 5078345, dtype: float64

In [72]:
import numpy as np
safe_std = sender_std.replace(0, np.nan)
safe_std

213094     1.606187e+05
824237     1.606187e+05
824238     1.606187e+05
1541411    1.606187e+05
1541410    1.606187e+05
               ...
892752     2.460852e+06
641019              NaN
244392     4.455844e+07
557982     4.455844e+07
244394              NaN
Name: amount_paid, Length: 5078345, dtype: float64

In [73]:
dataset["amount_paid_zscore"] = (dataset["amount_paid"] - sender_mean) / safe_std
dataset["amount_paid_zscore"]

213094    -3.412576
824237     0.573527
824238    -0.086016
1541411   -0.086016
1541410    0.573527
             ...
892752     0.707107
641019          NaN
244392     0.707107
557982    -0.707107
244394          NaN
Name: amount_paid_zscore, Length: 5078345, dtype: float64

In [74]:
dataset[dataset["amount_paid_zscore"] >= 3.0]

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,transaction_date,sender_daily_txn_count,sender_daily_amount,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders,high_fan_in_receiver,amount_paid_zscore
213347,2022-09-01 00:12:00+00:00,10057,803AB8EB0,110057,803B907F0,4.018941e+06,Yen,4.018941e+06,Yen,Wire,...,2022-09-01,8,1.404205e+07,3,2022-09-01 00:12:00+00:00,0.0,1,4,0,3.088509
556337,2022-09-01 07:07:00+00:00,10057,803AD5880,10057,803AD5880,1.467050e+07,Yen,1.467050e+07,Yen,Reinvestment,...,2022-09-01,16,4.180596e+07,6,2022-09-01 06:23:00+00:00,44.0,0,3,0,3.962684
673363,2022-09-01 10:47:00+00:00,10057,803AD5880,10060,8040362B0,1.559722e+07,Yen,1.559722e+07,Yen,Cheque,...,2022-09-01,16,4.180596e+07,6,2022-09-01 07:07:00+00:00,220.0,0,4,0,4.243775
1587906,2022-09-02 14:45:00+00:00,10057,803AF3DB0,212048,80C42B950,1.457874e+09,Yen,1.457874e+09,Yen,Wire,...,2022-09-02,10,2.816169e+09,4,2022-09-02 14:42:00+00:00,3.0,1,5,1,5.287329
1025285,2022-09-01 21:06:00+00:00,10057,803AFC4A0,10057,803AFC4A0,2.981251e+08,Yen,2.981251e+08,Yen,Reinvestment,...,2022-09-01,3,2.995877e+08,2,2022-09-01 03:54:00+00:00,1032.0,0,7,1,3.749979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507043,2022-09-01 05:35:00+00:00,9,806ECA9D0,9,806ECA9D0,2.674622e+06,Ruble,2.674622e+06,Ruble,Reinvestment,...,2022-09-01,3,2.709939e+06,2,NaT,NaN,0,3,0,3.614593
242379,2022-09-01 00:04:00+00:00,9,80711D3C0,9,80711D3C0,9.648155e+06,Ruble,9.648155e+06,Ruble,Reinvestment,...,2022-09-01,2,9.758943e+06,2,NaT,NaN,0,3,0,3.015113
242544,2022-09-01 00:07:00+00:00,9,807147BA0,9,807147BA0,2.871788e+07,Ruble,2.871788e+07,Ruble,Reinvestment,...,2022-09-01,4,2.900392e+07,2,2022-09-01 00:04:00+00:00,3.0,1,3,0,3.749722
758761,2022-09-01 13:04:00+00:00,9,8072AA760,9,8072AA760,1.227502e+05,Ruble,1.227502e+05,Ruble,Reinvestment,...,2022-09-01,5,1.560377e+05,2,2022-09-01 04:44:00+00:00,500.0,0,2,0,4.533000
624541,2022-09-01 09:27:00+00:00,9,8073D58F0,9,8073D58F0,3.327483e+07,Ruble,3.327483e+07,Ruble,Reinvestment,...,2022-09-01,4,3.352834e+07,2,2022-09-01 03:14:00+00:00,373.0,0,3,0,4.476864

In [75]:
dataset["high_amount_deviation"] = (dataset["amount_paid_zscore"] >= 3.0).astype(int)
dataset

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,sender_daily_txn_count,sender_daily_amount,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders,high_fan_in_receiver,amount_paid_zscore,high_amount_deviation
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,...,3,1615413.57,2,NaT,NaN,0,1,0,-3.412576,0
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,3,1615413.57,2,2022-09-01 00:19:00+00:00,881.0,0,3,0,0.573527,0
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,3,1615413.57,2,2022-09-01 15:00:00+00:00,2.0,1,3,0,-0.086016,0
1541411,2022-09-02 13:03:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,2,1468459.30,1,2022-09-01 15:02:00+00:00,1321.0,0,3,0,-0.086016,0
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,2,1468459.30,1,2022-09-02 13:03:00+00:00,2.0,1,3,0,0.573527,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892752,2022-09-01 17:00:00+00:00,9,8074FDFF0,9,8074FDFF0,3481092.47,Ruble,3481092.47,Ruble,Reinvestment,...,2,3482015.29,1,2022-09-01 00:25:00+00:00,995.0,0,4,0,0.707107,0
641019,2022-09-01 09:53:00+00:00,9,8074FF440,9,8074FF440,4434071.16,Ruble,4434071.16,Ruble,Reinvestment,...,1,4434071.16,1,NaT,NaN,0,3,0,NaN,0
244392,2022-09-01 00:02:00+00:00,9,8075352F0,9,8075352F0,63015743.94,Ruble,63015743.94,Ruble,Reinvestment,...,2,63016336.40,1,NaT,NaN,0,5,1,0.707107,0
557982,2022-09-01 07:01:00+00:00,9,8075352F0,9,8075352F0,592.46,Ruble,592.46,Ruble,Reinvestment,...,2,63016336.40,1,2022-09-01 00:02:00+00:00,419.0,0,5,1,-0.707107,0
244394,2022-09-01 00:16:00+00:00,9,8075370F0,9,8075370F0,30368.50,Ruble,30368.50,Ruble,Reinvestment,...,1,30368.50,1,NaT,NaN,0,3,0,NaN,0

In [77]:
dataset.columns

Index(['timestamp', 'from_bank', 'account', 'to_bank', 'account_1',
       'amount_received', 'receiving_currency', 'amount_paid',
       'payment_currency', 'payment_format', 'is_laundering', 'sender_entity',
       'receiver_entity', 'transaction_id', 'transaction_date',
       'sender_daily_txn_count', 'sender_daily_amount',
       'sender_daily_unique_receivers', 'previous_sender_timestamp',
       'mins_since_previous_sender_transaction', 'rapid_repeat_transfer',
       'receiver_unique_senders', 'high_fan_in_receiver', 'amount_paid_zscore',
       'high_amount_deviation'],
      dtype='object')

In [82]:
dataset["is_unusual_hour"] = (dataset["timestamp"].dt.hour.isin([0,1,2,3,4,5]).astype(int))
dataset.head(20)

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,sender_daily_amount,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders,high_fan_in_receiver,amount_paid_zscore,high_amount_deviation,is_unusual_hour
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,...,1615413.57,2,NaT,NaN,0,1,0,-3.412576,0,1
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1615413.57,2,2022-09-01 00:19:00+00:00,881.0,0,3,0,0.573527,0,0
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1615413.57,2,2022-09-01 15:00:00+00:00,2.0,1,3,0,-0.086016,0,0
1541411,2022-09-02 13:03:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1468459.30,1,2022-09-01 15:02:00+00:00,1321.0,0,3,0,-0.086016,0,0
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1468459.30,1,2022-09-02 13:03:00+00:00,2.0,1,3,0,0.573527,0,0
2570347,2022-09-05 13:53:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1468459.30,1,2022-09-02 13:05:00+00:00,4368.0,0,3,0,-0.086016,0,0
2570346,2022-09-05 13:59:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1468459.30,1,2022-09-05 13:53:00+00:00,6.0,1,3,0,0.573527,0,0
2798191,2022-09-06 00:36:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1468459.30,1,2022-09-05 13:59:00+00:00,637.0,0,3,0,-0.086016,0,1
2798190,2022-09-06 00:56:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1468459.30,1,2022-09-06 00:36:00+00:00,20.0,0,3,0,0.573527,0,1
3437164,2022-09-07 08:47:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1468459.30,1,2022-09-06 00:56:00+00:00,1911.0,0,3,0,-0.086016,0,0
3437163,2022-09-07 08:49:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1468459.30,1,2022-09-07 08:47:00+00:00,2.0,1,3,0,0.573527,0,0
3918768,2022-09-08 08:46:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1468459.30,1,2022-09-07 08:49:00+00:00,1437.0,0,3,0,0.573527,0,0
3918769,2022-09-08 08:58:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1468459.30,1,2022-09-08 08:46:00+00:00,12.0,0,3,0,-0.086016,0,0
4278714,2022-09-09 01:37:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1468459.30,1,2022-09-08 08:58:00+00:00,999.0,0,3,0,0.573527,0,1
4278715,2022-09-09 01:37:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1468459.30,1,2022-09-09 01:37:00+00:00,0.0,1,3,0,-0.086016,0,1
673518,2022-09-01 10:38:00+00:00,10057,803AA8E90,10099,804672160,667157.92,Yen,667157.92,Yen,Credit Card,...,21445655.15,4,NaT,NaN,0,3,0,-0.568354,0,0
673517,2022-09-01 10:51:00+00:00,10057,803AA8E90,10099,804672160,93486.14,Yen,93486.14,Yen,Cheque,...,21445655.15,4,2022-09-01 10:38:00+00:00,13.0,0,3,0,-0.691883,0,0
740365,2022-09-01 12:36:00+00:00,10057,803AA8E90,21,803B27D80,308178.75,Yen,308178.75,Yen,Cheque,...,21445655.15,4,2022-09-01 10:51:00+00:00,105.0,0,5,1,-0.645653,0,0
740366,2022-09-01 12:53:00+00:00,10057,803AA8E90,21,803B27D80,128133.20,Yen,128133.20,Yen,Credit Card,...,21445655.15,4,2022-09-01 12:36:00+00:00,17.0,0,5,1,-0.684422,0,0
807525,2022-09-01 14:34:00+00:00,10057,803AA8E90,19925,803F96510,7402694.77,Yen,7402694.77,Yen,Cash,...,21445655.15,4,2022-09-01 12:53:00+00:00,101.0,0,3,0,0.882012,0,0

In [86]:
# Rounding Amount Unusual Pattern
dataset["is_round_amount"] = ((dataset["amount_paid"] >= 10000) & (dataset["amount_paid"] % 1000 == 0)).astype(int)
dataset.head(20)

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders,high_fan_in_receiver,amount_paid_zscore,high_amount_deviation,is_unusual_hour,is_round_amount
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,...,2,NaT,NaN,0,1,0,-3.412576,0,1,0
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,2,2022-09-01 00:19:00+00:00,881.0,0,3,0,0.573527,0,0,0
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,2,2022-09-01 15:00:00+00:00,2.0,1,3,0,-0.086016,0,0,0
1541411,2022-09-02 13:03:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1,2022-09-01 15:02:00+00:00,1321.0,0,3,0,-0.086016,0,0,0
1541410,2022-09-02 13:05:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1,2022-09-02 13:03:00+00:00,2.0,1,3,0,0.573527,0,0,0
2570347,2022-09-05 13:53:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1,2022-09-02 13:05:00+00:00,4368.0,0,3,0,-0.086016,0,0,0
2570346,2022-09-05 13:59:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1,2022-09-05 13:53:00+00:00,6.0,1,3,0,0.573527,0,0,0
2798191,2022-09-06 00:36:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1,2022-09-05 13:59:00+00:00,637.0,0,3,0,-0.086016,0,1,0
2798190,2022-09-06 00:56:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1,2022-09-06 00:36:00+00:00,20.0,0,3,0,0.573527,0,1,0
3437164,2022-09-07 08:47:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1,2022-09-06 00:56:00+00:00,1911.0,0,3,0,-0.086016,0,0,0
3437163,2022-09-07 08:49:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1,2022-09-07 08:47:00+00:00,2.0,1,3,0,0.573527,0,0,0
3918768,2022-09-08 08:46:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1,2022-09-07 08:49:00+00:00,1437.0,0,3,0,0.573527,0,0,0
3918769,2022-09-08 08:58:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1,2022-09-08 08:46:00+00:00,12.0,0,3,0,-0.086016,0,0,0
4278714,2022-09-09 01:37:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,1,2022-09-08 08:58:00+00:00,999.0,0,3,0,0.573527,0,1,0
4278715,2022-09-09 01:37:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,1,2022-09-09 01:37:00+00:00,0.0,1,3,0,-0.086016,0,1,0
673518,2022-09-01 10:38:00+00:00,10057,803AA8E90,10099,804672160,667157.92,Yen,667157.92,Yen,Credit Card,...,4,NaT,NaN,0,3,0,-0.568354,0,0,0
673517,2022-09-01 10:51:00+00:00,10057,803AA8E90,10099,804672160,93486.14,Yen,93486.14,Yen,Cheque,...,4,2022-09-01 10:38:00+00:00,13.0,0,3,0,-0.691883,0,0,0
740365,2022-09-01 12:36:00+00:00,10057,803AA8E90,21,803B27D80,308178.75,Yen,308178.75,Yen,Cheque,...,4,2022-09-01 10:51:00+00:00,105.0,0,5,1,-0.645653,0,0,0
740366,2022-09-01 12:53:00+00:00,10057,803AA8E90,21,803B27D80,128133.20,Yen,128133.20,Yen,Credit Card,...,4,2022-09-01 12:36:00+00:00,17.0,0,5,1,-0.684422,0,0,0
807525,2022-09-01 14:34:00+00:00,10057,803AA8E90,19925,803F96510,7402694.77,Yen,7402694.77,Yen,Cash,...,4,2022-09-01 12:53:00+00:00,101.0,0,3,0,0.882012,0,0,0

In [87]:
dataset[dataset["is_round_amount"] == 1]

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,sender_daily_unique_receivers,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders,high_fan_in_receiver,amount_paid_zscore,high_amount_deviation,is_unusual_hour,is_round_amount
220522,2022-09-01 00:01:00+00:00,10099,80C4602C0,10060,80C460EB0,282000.0,Yen,282000.0,Yen,ACH,...,2,NaT,NaN,0,1,0,0.150063,0,1,1
623181,2022-09-01 09:07:00+00:00,10605,80444B8A0,11128,80446B2D0,13257000.0,Yen,13257000.0,Yen,ACH,...,2,2022-09-01 00:19:00+00:00,528.0,0,1,0,0.707107,0,0,1
891646,2022-09-01 17:16:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,2,2022-09-01 17:01:00+00:00,15.0,0,2,0,-0.749849,0,0,1
1155908,2022-09-02 00:42:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,1,2022-09-01 20:49:00+00:00,233.0,0,2,0,-0.749849,0,1,1
1947459,2022-09-03 07:39:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,1,2022-09-02 00:56:00+00:00,1843.0,0,2,0,-0.749849,0,0,1
2271752,2022-09-04 22:06:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,1,2022-09-04 22:01:00+00:00,5.0,1,2,0,-0.749849,0,0,1
2560882,2022-09-05 13:20:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,1,2022-09-05 13:20:00+00:00,0.0,1,2,0,-0.749849,0,0,1
2877127,2022-09-06 04:51:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,1,2022-09-06 04:37:00+00:00,14.0,0,2,0,-0.749849,0,1,1
3266231,2022-09-07 00:09:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,1,2022-09-07 00:05:00+00:00,4.0,1,2,0,-0.749849,0,1,1
3763559,2022-09-08 00:53:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,1,2022-09-08 00:46:00+00:00,7.0,1,2,0,-0.749849,0,1,1
4719691,2022-09-09 18:09:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,1,2022-09-09 18:06:00+00:00,3.0,1,2,0,-0.749849,0,0,1
4997103,2022-09-10 13:59:00+00:00,10813,80422CCC0,21,812C02CD0,95000.0,Yen,95000.0,Yen,ACH,...,1,2022-09-10 13:46:00+00:00,13.0,0,2,0,-0.749849,0,0,1
815515,2022-09-01 15:29:00+00:00,111425,806785E70,111443,806785EC0,169000.0,US Dollar,169000.0,US Dollar,Cheque,...,5,2022-09-01 08:11:00+00:00,438.0,0,2,0,2.065347,0,0,1
432497,2022-09-01 03:42:00+00:00,1244,80D4C5D70,33780,80D4B3CF0,1575000.0,US Dollar,1575000.0,US Dollar,Cheque,...,3,2022-09-01 00:27:00+00:00,195.0,0,1,0,1.499997,0,1,1
733257,2022-09-01 12:35:00+00:00,1412,80B9DA220,1412,80B9DA220,594000.0,US Dollar,594000.0,US Dollar,Reinvestment,...,2,2022-09-01 00:07:00+00:00,748.0,0,3,0,1.153516,0,0,1
627333,2022-09-01 09:05:00+00:00,14,80FE5B820,119,80FE5B960,22712000.0,Shekel,22712000.0,Shekel,Cheque,...,2,2022-09-01 00:29:00+00:00,516.0,0,1,0,0.707107,0,0,1
447675,2022-09-01 04:19:00+00:00,16333,807D96A00,22345,807D962F0,582000.0,US Dollar,582000.0,US Dollar,Cheque,...,2,NaT,NaN,0,1,0,0.707107,0,1,1
1075639,2022-09-01 22:31:00+00:00,210292,803D930F0,210292,804229550,3544000.0,Yen,3544000.0,Yen,Cheque,...,5,2022-09-01 11:19:00+00:00,672.0,0,3,0,-0.386731,0,0,1
741834,2022-09-01 12:49:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,4,2022-09-01 03:30:00+00:00,559.0,0,2,0,0.510376,0,0,1
1589028,2022-09-02 14:58:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,3,2022-09-02 14:54:00+00:00,4.0,1,2,0,0.510376,0,0,1
2027672,2022-09-03 17:36:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,2,2022-09-03 17:33:00+00:00,3.0,1,2,0,0.510376,0,0,1
2123591,2022-09-04 03:58:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,2,2022-09-04 03:56:00+00:00,2.0,1,2,0,0.510376,0,1,1
2473710,2022-09-05 08:46:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,2,2022-09-05 03:51:00+00:00,295.0,0,2,0,0.510376,0,0,1
3208945,2022-09-06 21:48:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,2,2022-09-06 21:39:00+00:00,9.0,1,2,0,0.510376,0,0,1
3525429,2022-09-07 13:11:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,2,2022-09-07 05:26:00+00:00,465.0,0,2,0,0.510376,0,0,1
3832474,2022-09-08 04:18:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,2,2022-09-08 04:08:00+00:00,10.0,1,2,0,0.510376,0,1,1
4640019,2022-09-09 15:19:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,3,2022-09-09 15:13:00+00:00,6.0,1,2,0,0.510376,0,0,1
4957161,2022-09-10 08:41:00+00:00,217641,806A26240,116843,80741CF50,1671000.0,Ruble,1671000.0,Ruble,Credit Card,...,2,2022-09-10 08:40:00+00:00,1.0,1,2,0,0.510376,0,0,1
189754,2022-09-01 00:16:00+00:00,21831,81273EEF0,21831,81273EEF0,548000.0,Euro,548000.0,Euro,Reinvestment,...,1,NaT,NaN,0,3,0,NaN,0,1,1
34373,2022-09-01 00:26:00+00:00,23402,804945680,12446,804946E30,7993000.0,US Dollar,7993000.0,US Dollar,Cheque,...,2,2022-09-01 00:02:00+00:00,24.0,0,1,0,0.707107,0,1,1
1114095,2022-09-01 23:57:00+00:00,243897,80FFCB4D0,113,80FFBA170,44805000.0,Shekel,44805000.0,Shekel,Cheque,...,2,2022-09-01 00:07:00+00:00,1430.0,0,1,0,1.154695,0,0,1
1009838,2022-09-01 20:44:00+00:00,287,806556960,287,806556960,1579000.0,Ruble,1579000.0,Ruble,Reinvestment,...,1,NaT,NaN,0,1,0,-1.005170,0,0,1
790421,2022-09-01 14:16:00+00:00,29788,8038E2630,5627,80CAFEAC0,34695000.0,Yuan,34695000.0,Yuan,Cheque,...,6,2022-09-01 14:14:00+00:00,2.0,1,3,0,4.809314,1,0,1
62941,2022-09-01 00:12:00+00:00,4523,809FAACC0,224449,809FAA490,727000.0,US Dollar,727000.0,US Dollar,Cheque,...,2,NaT,NaN,0,1,0,0.707107,0,1,1
1133654,2022-09-02 00:07:00+00:00,8248,8035F5F50,18067,8035F7060,43643000.0,Yuan,43643000.0,Yuan,Cheque,...,2,2022-09-01 13:21:00+00:00,646.0,0,1,0,5.569733,1,1,1

In [88]:
dataset.columns

Index(['timestamp', 'from_bank', 'account', 'to_bank', 'account_1',
       'amount_received', 'receiving_currency', 'amount_paid',
       'payment_currency', 'payment_format', 'is_laundering', 'sender_entity',
       'receiver_entity', 'transaction_id', 'transaction_date',
       'sender_daily_txn_count', 'sender_daily_amount',
       'sender_daily_unique_receivers', 'previous_sender_timestamp',
       'mins_since_previous_sender_transaction', 'rapid_repeat_transfer',
       'receiver_unique_senders', 'high_fan_in_receiver', 'amount_paid_zscore',
       'high_amount_deviation', 'is_unusual_hour', 'is_round_amount'],
      dtype='object')

In [92]:
dataset["potential_structuring"] = ((dataset["sender_daily_txn_count"] >= 3) & (dataset["sender_daily_amount"] >= 10000)).astype(int)
dataset[dataset["potential_structuring"] == 1]

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,previous_sender_timestamp,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders,high_fan_in_receiver,amount_paid_zscore,high_amount_deviation,is_unusual_hour,is_round_amount,potential_structuring
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,...,NaT,NaN,0,1,0,-3.412576,0,1,0,1
824237,2022-09-01 15:00:00+00:00,10057,803A115E0,29467,803E020C0,787197.11,Yen,787197.11,Yen,Cheque,...,2022-09-01 00:19:00+00:00,881.0,0,3,0,0.573527,0,0,0,1
824238,2022-09-01 15:02:00+00:00,10057,803A115E0,29467,803E020C0,681262.19,Yen,681262.19,Yen,Credit Card,...,2022-09-01 15:00:00+00:00,2.0,1,3,0,-0.086016,0,0,0,1
673518,2022-09-01 10:38:00+00:00,10057,803AA8E90,10099,804672160,667157.92,Yen,667157.92,Yen,Credit Card,...,NaT,NaN,0,3,0,-0.568354,0,0,0,1
673517,2022-09-01 10:51:00+00:00,10057,803AA8E90,10099,804672160,93486.14,Yen,93486.14,Yen,Cheque,...,2022-09-01 10:38:00+00:00,13.0,0,3,0,-0.691883,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4253085,2022-09-09 00:50:00+00:00,9,8072AA760,220042,807438570,15134.05,Ruble,15134.05,Ruble,ACH,...,2022-09-09 00:49:00+00:00,1.0,1,3,0,-0.004140,0,1,0,1
373183,2022-09-01 01:30:00+00:00,9,8073D58F0,218783,8073D4970,212543.02,Ruble,212543.02,Ruble,Credit Card,...,NaT,NaN,0,7,1,-0.200112,0,1,0,1
373182,2022-09-01 01:55:00+00:00,9,8073D58F0,218783,8073D4970,39601.40,Ruble,39601.40,Ruble,Cheque,...,2022-09-01 01:30:00+00:00,25.0,0,7,1,-0.224576,0,1,0,1
423790,2022-09-01 03:14:00+00:00,9,8073D58F0,9,8073D58F0,1368.21,Ruble,1368.21,Ruble,Reinvestment,...,2022-09-01 01:55:00+00:00,79.0,0,3,0,-0.229985,0,1,0,1
624541,2022-09-01 09:27:00+00:00,9,8073D58F0,9,8073D58F0,33274829.47,Ruble,33274829.47,Ruble,Reinvestment,...,2022-09-01 03:14:00+00:00,373.0,0,3,0,4.476864,1,0,0,1

In [94]:
dataset["self_transfer"] = (dataset["sender_entity"] == dataset["receiver_entity"]).astype(int)
dataset[dataset["self_transfer"] == 1]

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,...,mins_since_previous_sender_transaction,rapid_repeat_transfer,receiver_unique_senders,high_fan_in_receiver,amount_paid_zscore,high_amount_deviation,is_unusual_hour,is_round_amount,potential_structuring,self_transfer
213094,2022-09-01 00:19:00+00:00,10057,803A115E0,10057,803A115E0,146954.27,Yen,146954.27,Yen,Reinvestment,...,NaN,0,1,0,-3.412576,0,1,0,1,1
606523,2022-09-01 08:42:00+00:00,10057,803AAB430,10057,803AAB430,131419.05,Yen,131419.05,Yen,Reinvestment,...,494.0,0,3,0,-0.820748,0,0,0,1,1
212654,2022-09-01 00:05:00+00:00,10057,803AACE20,10057,803AACE20,458.66,Yen,458.66,Yen,Reinvestment,...,1.0,1,3,0,-0.792668,0,1,0,1,1
723767,2022-09-01 12:13:00+00:00,10057,803AACE20,10057,803AACE20,14801669.82,Yen,14801669.82,Yen,Reinvestment,...,532.0,0,3,0,0.895207,0,0,0,1,1
991933,2022-09-01 20:25:00+00:00,10057,803AB4F70,10057,803AB4F70,2810787.05,Yen,2810787.05,Yen,Reinvestment,...,632.0,0,4,0,0.637136,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892752,2022-09-01 17:00:00+00:00,9,8074FDFF0,9,8074FDFF0,3481092.47,Ruble,3481092.47,Ruble,Reinvestment,...,995.0,0,4,0,0.707107,0,0,0,0,1
641019,2022-09-01 09:53:00+00:00,9,8074FF440,9,8074FF440,4434071.16,Ruble,4434071.16,Ruble,Reinvestment,...,NaN,0,3,0,NaN,0,0,0,0,1
244392,2022-09-01 00:02:00+00:00,9,8075352F0,9,8075352F0,63015743.94,Ruble,63015743.94,Ruble,Reinvestment,...,NaN,0,5,1,0.707107,0,1,0,0,1
557982,2022-09-01 07:01:00+00:00,9,8075352F0,9,8075352F0,592.46,Ruble,592.46,Ruble,Reinvestment,...,419.0,0,5,1,-0.707107,0,0,0,0,1
244394,2022-09-01 00:16:00+00:00,9,8075370F0,9,8075370F0,30368.50,Ruble,30368.50,Ruble,Reinvestment,...,NaN,0,3,0,NaN,0,1,0,0,1